"""add_source_category_to_event_lake

Revision ID: 0f2bc2a7c5d5
Revises: 62e1fd881740
Create Date: 2026-02-19 03:07:07.912963

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f2bc2a7c5d5"
down_revision: str | Sequence[str] | None = "62e1fd881740"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("event_lake", sa.Column("source_category", sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("event_lake", "source_category")
    # ### end Alembic commands ###
