"""achievement_system_v2_categories_rarities_series_triggers

Revision ID: 30a6c3f7d3eb
Revises: f3a7b9d2e1c6
Create Date: 2026-02-14 00:11:11.194161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30a6c3f7d3eb'
down_revision: Union[str, Sequence[str], None] = 'f3a7b9d2e1c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievement_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='uq_achiev_categories_guild_name')
    )
    op.create_table('achievement_rarities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='uq_achiev_rarities_guild_name')
    )
    op.create_table('achievement_series',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('guild_id', 'name', name='uq_achiev_series_guild_name')
    )
    op.add_column('achievement_templates', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('achievement_templates', sa.Column('rarity_id', sa.Integer(), nullable=True))
    op.add_column('achievement_templates', sa.Column('trigger_type', sa.String(length=30), nullable=False, server_default='manual'))
    op.add_column('achievement_templates', sa.Column('trigger_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('achievement_templates', sa.Column('series_id', sa.Integer(), nullable=True))
    op.add_column('achievement_templates', sa.Column('series_order', sa.Integer(), nullable=True))
    op.add_column('achievement_templates', sa.Column('badge_image', sa.String(length=500), nullable=True))
    op.add_column('achievement_templates', sa.Column('is_hidden', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('achievement_templates', sa.Column('max_earners', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'achievement_templates', 'achievement_rarities', ['rarity_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'achievement_templates', 'achievement_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'achievement_templates', 'achievement_series', ['series_id'], ['id'], ondelete='SET NULL')
    op.drop_column('achievement_templates', 'badge_image_url')
    op.drop_column('achievement_templates', 'requirement_scope')
    op.drop_column('achievement_templates', 'category')
    op.drop_column('achievement_templates', 'requirement_type')
    op.drop_column('achievement_templates', 'requirement_value')
    op.drop_column('achievement_templates', 'requirement_field')
    op.drop_column('achievement_templates', 'rarity')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievement_templates', sa.Column('rarity', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('achievement_templates', sa.Column('requirement_field', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('achievement_templates', sa.Column('requirement_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('achievement_templates', sa.Column('requirement_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('achievement_templates', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('achievement_templates', sa.Column('requirement_scope', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.add_column('achievement_templates', sa.Column('badge_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'achievement_templates', type_='foreignkey')
    op.drop_constraint(None, 'achievement_templates', type_='foreignkey')
    op.drop_constraint(None, 'achievement_templates', type_='foreignkey')
    op.drop_column('achievement_templates', 'max_earners')
    op.drop_column('achievement_templates', 'is_hidden')
    op.drop_column('achievement_templates', 'badge_image')
    op.drop_column('achievement_templates', 'series_order')
    op.drop_column('achievement_templates', 'series_id')
    op.drop_column('achievement_templates', 'trigger_config')
    op.drop_column('achievement_templates', 'trigger_type')
    op.drop_column('achievement_templates', 'rarity_id')
    op.drop_column('achievement_templates', 'category_id')
    op.drop_table('achievement_series')
    op.drop_table('achievement_rarities')
    op.drop_table('achievement_categories')
    # ### end Alembic commands ###
