"""initial_schema

Revision ID: 62e1fd881740
Revises:
Create Date: 2026-02-19 02:55:50.238055

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62e1fd881740"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievement_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "name", name="uq_achiev_categories_guild_name"),
    )
    op.create_table(
        "achievement_rarities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("color", sa.String(length=7), nullable=False),
        sa.Column("emoji", sa.String(length=10), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "name", name="uq_achiev_rarities_guild_name"),
    )
    op.create_table(
        "achievement_series",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "name", name="uq_achiev_series_guild_name"),
    )
    op.create_table(
        "admin_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=False),
        sa.Column("action_type", sa.String(length=50), nullable=False),
        sa.Column("target_table", sa.String(length=50), nullable=False),
        sa.Column("target_id", sa.String(length=100), nullable=True),
        sa.Column("before_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_admin_log_actor_time", "admin_log", ["actor_id", "timestamp"], unique=False
    )
    op.create_index(
        "ix_admin_log_target",
        "admin_log",
        ["target_table", "target_id", "timestamp"],
        unique=False,
    )
    op.create_table(
        "admin_rate_limit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("admin_id", sa.String(length=64), nullable=False),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_admin_rate_limit_admin_ts",
        "admin_rate_limit_events",
        ["admin_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "ix_admin_rate_limit_ts", "admin_rate_limit_events", ["timestamp"], unique=False
    )
    op.create_table(
        "channel_overrides",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("xp_multiplier", sa.Float(), nullable=False),
        sa.Column("star_multiplier", sa.Float(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "guild_id", "channel_id", "event_type", name="uq_overrides_guild_channel_event"
        ),
    )
    op.create_index("ix_overrides_channel", "channel_overrides", ["channel_id"], unique=False)
    op.create_table(
        "channel_type_defaults",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("channel_type", sa.String(length=20), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("xp_multiplier", sa.Float(), nullable=False),
        sa.Column("star_multiplier", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "guild_id", "channel_type", "event_type", name="uq_type_defaults_guild_type_event"
        ),
    )
    op.create_index("ix_type_defaults_guild", "channel_type_defaults", ["guild_id"], unique=False)
    op.create_table(
        "channels",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("discord_category_id", sa.BigInteger(), nullable=True),
        sa.Column("discord_category_name", sa.String(length=100), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "last_synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_channels_guild_id", "channels", ["guild_id"], unique=False)
    op.create_table(
        "event_counters",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=16), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", "event_type", "period"),
    )
    op.create_table(
        "event_lake",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("channel_id", sa.BigInteger(), nullable=True),
        sa.Column("target_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "payload", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("source_id", sa.String(length=128), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_event_lake_channel_ts",
        "event_lake",
        ["channel_id", sa.literal_column("timestamp DESC")],
        unique=False,
        postgresql_where=sa.text("channel_id IS NOT NULL"),
    )
    op.create_index(
        "idx_event_lake_guild_ts",
        "event_lake",
        ["guild_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "idx_event_lake_source",
        "event_lake",
        ["source_id"],
        unique=True,
        postgresql_where=sa.text("source_id IS NOT NULL"),
    )
    op.create_index(
        "idx_event_lake_type_ts",
        "event_lake",
        ["event_type", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_index(
        "idx_event_lake_user_ts",
        "event_lake",
        ["user_id", sa.literal_column("timestamp DESC")],
        unique=False,
    )
    op.create_table(
        "media_folders",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["media_folders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "guild_id", "parent_id", "name", name="uq_media_folders_guild_parent_name"
        ),
    )
    op.create_index("ix_media_folders_guild", "media_folders", ["guild_id"], unique=False)
    op.create_table(
        "oauth_states",
        sa.Column("state", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("state"),
    )
    op.create_index("ix_oauth_states_created_at", "oauth_states", ["created_at"], unique=False)
    op.create_table(
        "page_layouts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("page_slug", sa.String(length=50), nullable=False),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("layout_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "page_slug", name="uq_page_layouts_guild_slug"),
    )
    op.create_table(
        "projection_checkpoints",
        sa.Column("worker_id", sa.String(length=64), nullable=False),
        sa.Column("last_processed_evaluation_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("worker_id"),
    )
    op.create_table(
        "reward_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "predicates",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "outcomes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_rules_guild_priority", "reward_rules", ["guild_id", "priority"], unique=False
    )
    op.create_table(
        "rule_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("rules_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "version", name="uq_rule_snapshots_guild_version"),
    )
    op.create_index(
        "ix_rule_snapshots_guild_active", "rule_snapshots", ["guild_id", "is_active"], unique=False
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "name", name="uq_seasons_guild_name"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index("ix_settings_category", "settings", ["category"], unique=False)
    op.create_table(
        "svg_overlays",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("svg_url", sa.String(length=500), nullable=False),
        sa.Column("preview_url", sa.String(length=500), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "name", name="uq_svg_overlays_guild_name"),
    )
    op.create_index("ix_svg_overlays_guild", "svg_overlays", ["guild_id"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("avatar_url", sa.String(length=500), nullable=True),
        sa.Column("left_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("discord_id"),
    )
    op.create_index("ix_user_profiles_guild", "user_profiles", ["guild_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("discord_name", sa.String(length=100), nullable=False),
        sa.Column("discord_avatar_hash", sa.String(length=100), nullable=True),
        sa.Column("github_username", sa.String(length=39), nullable=True),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("gold", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_users_xp_desc", "users", ["xp"], unique=False)
    op.create_table(
        "achievement_templates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("rarity_id", sa.Integer(), nullable=True),
        sa.Column("season_id", sa.Integer(), nullable=True),
        sa.Column("overlay_id", sa.Integer(), nullable=True),
        sa.Column("trigger_type", sa.String(length=30), nullable=False),
        sa.Column("trigger_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("series_id", sa.Integer(), nullable=True),
        sa.Column("series_order", sa.Integer(), nullable=True),
        sa.Column("xp_reward", sa.Integer(), nullable=False),
        sa.Column("gold_reward", sa.Integer(), nullable=False),
        sa.Column("badge_image", sa.String(length=500), nullable=True),
        sa.Column("announce_channel_id", sa.BigInteger(), nullable=True),
        sa.Column("is_hidden", sa.Boolean(), nullable=False),
        sa.Column("max_earners", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["achievement_categories.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["overlay_id"], ["svg_overlays.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rarity_id"], ["achievement_rarities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["series_id"], ["achievement_series.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("guild_id", "name", name="uq_achiev_templates_guild_name"),
    )
    op.create_table(
        "activity_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=True),
        sa.Column("source_system", sa.String(length=30), nullable=False),
        sa.Column("source_event_id", sa.String(length=100), nullable=True),
        sa.Column("xp_delta", sa.Integer(), nullable=False),
        sa.Column("star_delta", sa.Integer(), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_activity_log_event_time", "activity_log", ["event_type", "timestamp"], unique=False
    )
    op.create_index(
        "ix_activity_log_idempotent",
        "activity_log",
        ["source_system", "source_event_id"],
        unique=True,
        postgresql_where=sa.text("source_event_id IS NOT NULL"),
    )
    op.create_index("ix_activity_log_timestamp", "activity_log", ["timestamp"], unique=False)
    op.create_index(
        "ix_activity_log_user_time", "activity_log", ["user_id", "timestamp"], unique=False
    )
    op.create_table(
        "card_configs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("page_layout_id", sa.String(length=36), nullable=False),
        sa.Column("card_type", sa.String(length=50), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("grid_span", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=True),
        sa.Column("subtitle", sa.String(length=500), nullable=True),
        sa.Column("config_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["page_layout_id"], ["page_layouts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_card_configs_page_layout", "card_configs", ["page_layout_id", "position"], unique=False
    )
    op.create_table(
        "marketplace_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("item_type", sa.String(length=30), nullable=False),
        sa.Column("cost_xp", sa.Integer(), nullable=True),
        sa.Column("cost_gold", sa.Integer(), nullable=True),
        sa.Column("rarity_id", sa.Integer(), nullable=True),
        sa.Column("overlay_id", sa.Integer(), nullable=True),
        sa.Column("discord_role_id", sa.BigInteger(), nullable=True),
        sa.Column("season_id", sa.Integer(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["overlay_id"], ["svg_overlays.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["rarity_id"], ["achievement_rarities.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_marketplace_items_guild_active",
        "marketplace_items",
        ["guild_id", "active"],
        unique=False,
    )
    op.create_table(
        "media_files",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("alt_text", sa.String(length=200), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.BigInteger(), nullable=True),
        sa.Column("folder_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["folder_id"], ["media_folders.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index("ix_media_files_folder", "media_files", ["folder_id"], unique=False)
    op.create_index("ix_media_files_guild_id", "media_files", ["guild_id"], unique=False)
    op.create_table(
        "rule_evaluations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("event_lake_id", sa.BigInteger(), nullable=False),
        sa.Column("snapshot_id", sa.Integer(), nullable=True),
        sa.Column(
            "matched_rules",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "outcomes_applied",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "context_snapshot",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["event_lake_id"], ["event_lake.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["snapshot_id"], ["rule_snapshots.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rule_evaluations_event", "rule_evaluations", ["event_lake_id"], unique=False
    )
    op.create_index(
        "ix_rule_evaluations_guild_ts",
        "rule_evaluations",
        ["guild_id", "evaluated_at"],
        unique=False,
    )
    op.create_index(
        "ix_rule_evaluations_snapshot", "rule_evaluations", ["snapshot_id"], unique=False
    )
    op.create_table(
        "user_guild_roles",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("role_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("role_name", sa.String(length=100), nullable=True),
        sa.Column(
            "synced_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user_profiles.discord_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_index("ix_user_guild_roles_guild", "user_guild_roles", ["guild_id"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("announce_level_up", sa.Boolean(), nullable=False),
        sa.Column("announce_achievements", sa.Boolean(), nullable=False),
        sa.Column("announce_awards", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "user_stats",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("season_stars", sa.Integer(), nullable=False),
        sa.Column("lifetime_stars", sa.Integer(), nullable=False),
        sa.Column("messages_sent", sa.Integer(), nullable=False),
        sa.Column("reactions_given", sa.Integer(), nullable=False),
        sa.Column("reactions_received", sa.Integer(), nullable=False),
        sa.Column("threads_created", sa.Integer(), nullable=False),
        sa.Column("voice_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["season_id"], ["seasons.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "season_id"),
    )
    op.create_table(
        "user_achievements",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("achievement_id", sa.Integer(), nullable=False),
        sa.Column(
            "earned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["achievement_id"], ["achievement_templates.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "achievement_id"),
    )
    op.create_table(
        "user_inventory",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "purchased_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_equipped", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["item_id"], ["marketplace_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "item_id", name="uq_user_inventory_user_item"),
    )
    op.create_index("ix_user_inventory_guild", "user_inventory", ["guild_id"], unique=False)
    op.create_index("ix_user_inventory_user", "user_inventory", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_user_inventory_user", table_name="user_inventory")
    op.drop_index("ix_user_inventory_guild", table_name="user_inventory")
    op.drop_table("user_inventory")
    op.drop_table("user_achievements")
    op.drop_table("user_stats")
    op.drop_table("user_preferences")
    op.drop_index("ix_user_guild_roles_guild", table_name="user_guild_roles")
    op.drop_table("user_guild_roles")
    op.drop_index("ix_rule_evaluations_snapshot", table_name="rule_evaluations")
    op.drop_index("ix_rule_evaluations_guild_ts", table_name="rule_evaluations")
    op.drop_index("ix_rule_evaluations_event", table_name="rule_evaluations")
    op.drop_table("rule_evaluations")
    op.drop_index("ix_media_files_guild_id", table_name="media_files")
    op.drop_index("ix_media_files_folder", table_name="media_files")
    op.drop_table("media_files")
    op.drop_index("ix_marketplace_items_guild_active", table_name="marketplace_items")
    op.drop_table("marketplace_items")
    op.drop_index("ix_card_configs_page_layout", table_name="card_configs")
    op.drop_table("card_configs")
    op.drop_index("ix_activity_log_user_time", table_name="activity_log")
    op.drop_index("ix_activity_log_timestamp", table_name="activity_log")
    op.drop_index(
        "ix_activity_log_idempotent",
        table_name="activity_log",
        postgresql_where=sa.text("source_event_id IS NOT NULL"),
    )
    op.drop_index("ix_activity_log_event_time", table_name="activity_log")
    op.drop_table("activity_log")
    op.drop_table("achievement_templates")
    op.drop_index("ix_users_xp_desc", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_user_profiles_guild", table_name="user_profiles")
    op.drop_table("user_profiles")
    op.drop_index("ix_svg_overlays_guild", table_name="svg_overlays")
    op.drop_table("svg_overlays")
    op.drop_index("ix_settings_category", table_name="settings")
    op.drop_table("settings")
    op.drop_table("seasons")
    op.drop_index("ix_rule_snapshots_guild_active", table_name="rule_snapshots")
    op.drop_table("rule_snapshots")
    op.drop_index("idx_rules_guild_priority", table_name="reward_rules")
    op.drop_table("reward_rules")
    op.drop_table("projection_checkpoints")
    op.drop_table("page_layouts")
    op.drop_index("ix_oauth_states_created_at", table_name="oauth_states")
    op.drop_table("oauth_states")
    op.drop_index("ix_media_folders_guild", table_name="media_folders")
    op.drop_table("media_folders")
    op.drop_index("idx_event_lake_user_ts", table_name="event_lake")
    op.drop_index("idx_event_lake_type_ts", table_name="event_lake")
    op.drop_index(
        "idx_event_lake_source",
        table_name="event_lake",
        postgresql_where=sa.text("source_id IS NOT NULL"),
    )
    op.drop_index("idx_event_lake_guild_ts", table_name="event_lake")
    op.drop_index(
        "idx_event_lake_channel_ts",
        table_name="event_lake",
        postgresql_where=sa.text("channel_id IS NOT NULL"),
    )
    op.drop_table("event_lake")
    op.drop_table("event_counters")
    op.drop_index("ix_channels_guild_id", table_name="channels")
    op.drop_table("channels")
    op.drop_index("ix_type_defaults_guild", table_name="channel_type_defaults")
    op.drop_table("channel_type_defaults")
    op.drop_index("ix_overrides_channel", table_name="channel_overrides")
    op.drop_table("channel_overrides")
    op.drop_index("ix_admin_rate_limit_ts", table_name="admin_rate_limit_events")
    op.drop_index("ix_admin_rate_limit_admin_ts", table_name="admin_rate_limit_events")
    op.drop_table("admin_rate_limit_events")
    op.drop_index("ix_admin_log_target", table_name="admin_log")
    op.drop_index("ix_admin_log_actor_time", table_name="admin_log")
    op.drop_table("admin_log")
    op.drop_table("achievement_series")
    op.drop_table("achievement_rarities")
    op.drop_table("achievement_categories")
    # ### end Alembic commands ###
