"""nullable_event_lake_id_in_rule_evaluations

Revision ID: a6282fe1f494
Revises: 0f2bc2a7c5d5
Create Date: 2026-02-19 03:19:06.840285

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6282fe1f494"
down_revision: str | Sequence[str] | None = "0f2bc2a7c5d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("rule_evaluations", "event_lake_id", existing_type=sa.BIGINT(), nullable=True)
    op.drop_constraint(
        op.f("rule_evaluations_event_lake_id_fkey"), "rule_evaluations", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "rule_evaluations", "event_lake", ["event_lake_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rule_evaluations", type_="foreignkey")
    op.create_foreign_key(
        op.f("rule_evaluations_event_lake_id_fkey"),
        "rule_evaluations",
        "event_lake",
        ["event_lake_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("rule_evaluations", "event_lake_id", existing_type=sa.BIGINT(), nullable=False)
    # ### end Alembic commands ###
