"""add_user_id_to_rule_evaluations

Revision ID: c8a034d6e30e
Revises: a6282fe1f494
Create Date: 2026-02-19 03:46:06.113973

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c8a034d6e30e"
down_revision: str | Sequence[str] | None = "a6282fe1f494"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rule_evaluations", sa.Column("user_id", sa.BigInteger(), nullable=True))
    op.create_index("ix_rule_evaluations_user", "rule_evaluations", ["user_id"], unique=False)
    op.create_foreign_key(
        None, "rule_evaluations", "users", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "rule_evaluations", type_="foreignkey")
    op.drop_index("ix_rule_evaluations_user", table_name="rule_evaluations")
    op.drop_column("rule_evaluations", "user_id")
    # ### end Alembic commands ###
