"""Align_marketplace_item_types

Revision ID: f0be0607f872
Revises: a9c2d4e6f8b1
Create Date: 2026-02-19 16:33:08.853474

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f0be0607f872'
down_revision: str | Sequence[str] | None = 'a9c2d4e6f8b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_rate_limit_events', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###

    # Manual data migration for item types
    op.execute(
        "UPDATE marketplace_items SET item_type = 'DISCORD_ROLE' "
        "WHERE item_type = 'CUSTOM_ROLE_COLOR'"
    )
    op.execute(
        "UPDATE marketplace_items SET item_type = 'COSMETIC_OVERLAY' "
        "WHERE item_type = 'PROFILE_THEME'"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # Reverse data migration
    op.execute(
        "UPDATE marketplace_items SET item_type = 'CUSTOM_ROLE_COLOR' "
        "WHERE item_type = 'DISCORD_ROLE'"
    )
    op.execute(
        "UPDATE marketplace_items SET item_type = 'PROFILE_THEME' "
        "WHERE item_type = 'COSMETIC_OVERLAY'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_rate_limit_events', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
